# Generated by Django 4.0.2 on 2023-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=100)),
                ('classification_code', models.CharField(max_length=10)),
                ('classification_name', models.CharField(max_length=50)),
            ],
        ),
    ]
