# Generated by Django 4.1.7 on 2023-03-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('icd_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ICDBlock',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('count_diagnosis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ICDChapter',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('count_diagnosis', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DiagnosedResult',
        ),
        migrations.AddField(
            model_name='icdblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.icdchapter'),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.icdblock'),
        ),
    ]
