# Generated by Django 4.1.7 on 2023-03-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_icdblock_count_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresult',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.icdblock'),
        ),
        migrations.AlterField(
            model_name='icdblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.icdchapter'),
        ),
    ]
