# Generated by Django 4.1.7 on 2023-03-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_diagnosticresult_block_alter_icdblock_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresult',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.icdblock'),
        ),
    ]
